### ISSUE TITLE
Is the website down? Everything is timing out

### ISSUE THREAD

**Issue by dkoslicki** [dib-lab/wort#39]
I tried looking at the download link for the example SRA entry: https://wort.oxli.org/v1/view/sra/DRR013902 but am getting the following:
![image](https://user-images.githubusercontent.com/6362936/119751089-84462d80-be68-11eb-9af9-2b24a8790b16.png)
Same thing happens for pretty much any SRA, IMG, or NCBI assembly I try.
Are the servers overloaded or the like?

**Comment by luizirber** [comment]
Hi @dkoslicki! Thanks for pointing the problem!

So... the culprit is https://github.com/dib-lab/wort/commit/ad5ef1ea21a5051a115ab02a0d936402a82ee73d, where I defaulted to loading data from IPFS (instead of S3) if the dataset has an IPFS address. But despite having an IPFS address, the node containing the data is currently down :disappointed: 

I can revert back to the version providing data from S3, but I'm a bit nervous about making it the default because each download will incur data transfer costs (and I don't want to raise @ctb's AWS bill even more :sweat_smile:)

**Comment by dkoslicki** [comment]
Closing for out-of-band reasons
